def includeme(config):
    config.add_static_view('static', 'learning_journal_db:static')
    config.add_route('login', '/login')
    config.add_route('logout', '/logout')
    config.add_route('home', '/')
    config.add_route('lists', '/list')
    config.add_route('create', '/journal/new-entry')
    config.add_route('detail', '/journal/{id:\d+}')
    config.add_route('update', '/journal/{id:\d+}/edit-entry')
